namespace CoffeeShopApp.Patterns;


public interface IIvoiceAdapter
{
    void generateInvoice(string customer, decimal amount);
}

public class InvoiceAdapter : IIvoiceAdapter
{
    private readonly LegacySystem _legacySystem;
    public InvoiceAdapter(LegacySystem legacySystem)
    {
        _legacySystem = legacySystem;
    }
    public void generateInvoice(string customer, decimal amount)
    {
        Console.WriteLine(_legacySystem.legacyInvoiceGenerator(customer, amount));
    }
}

public class LegacySystem
{
    public string legacyInvoiceGenerator(string customer, decimal amount)
    {
        return $"Legacy Invoice Generated by {customer} amount {amount.ToString("0.00")} Taka.";
    }
}